services:
  ollama-server:
    build: ./ollama_docker
    container_name: ollama-server
    image: ssr1998/ollama-server:latest
    ports:
      - "11434:11434"
    restart: unless-stopped

  ollama-ragbot:
    build: ./chatbot_docker
    container_name: ollama-ragbot
    image: ssr1998/ollama-ragbot:latest
    depends_on:
      - ollama-server
    environment:
      - OLLAMA_API_URL=http://ollama-server:11434
      - OLLAMA_MODEL=llama3.2:1b
    stdin_open: true
    tty: true
